const sampleUsers = [
  {
    id: "demo-user-1",
    name: "Ravi Kumar",
    age: 34,
    state: "Karnataka",
    income: 120000,
    category: "OBC",
    occupation: "Farmer",
  },
  {
    id: "demo-user-2",
    name: "Priya Sharma",
    age: 27,
    state: "Maharashtra",
    income: 85000,
    category: "General",
    occupation: "Student",
  },
  {
    id: "demo-user-3",
    name: "Anjali Devi",
    age: 45,
    state: "Bihar",
    income: 60000,
    category: "SC",
    occupation: "Daily Wage Worker",
  },
  {
    id: "demo-user-4",
    name: "Mohammed Rafiq",
    age: 52,
    state: "Uttar Pradesh",
    income: 95000,
    category: "OBC",
    occupation: "Small Business Owner",
  },
];

const sampleSchemes = [
  {
    id: "1",
    name: "PM Kisan Samman Nidhi",
    category: "Agriculture",
    benefit: "Rs. 6000/year",
    eligibility: "Farmers with land under 2 hectares",
    state: "All India",
  },
  {
    id: "2",
    name: "PM Awas Yojana",
    category: "Housing",
    benefit: "Subsidy up to Rs. 2.67 lakh",
    eligibility: "EWS/LIG income group",
    state: "All India",
  },
  {
    id: "3",
    name: "Ayushman Bharat",
    category: "Health",
    benefit: "Rs. 5 lakh health cover/year",
    eligibility: "BPL families",
    state: "All India",
  },
  {
    id: "4",
    name: "Beti Bachao Beti Padhao",
    category: "Education",
    benefit: "Scholarships and awareness support",
    eligibility: "Girl child",
    state: "All India",
  },
  {
    id: "5",
    name: "Mudra Loan Yojana",
    category: "Business",
    benefit: "Loan up to Rs. 10 lakh",
    eligibility: "Small and micro business owners",
    state: "All India",
  },
  {
    id: "6",
    name: "Rajiv Gandhi Scholarships",
    category: "Education",
    benefit: "Rs. 12000/year",
    eligibility: "SC/ST students in Karnataka",
    state: "Karnataka",
  },
];

const sampleApplications = [
  {
    id: "demo-app-1",
    userId: "demo-user-1",
    schemeId: "1",
    schemeName: "PM Kisan Samman Nidhi",
    citizenName: "Ravi Kumar",
    ministry: "Ministry of Agriculture",
    state: "Karnataka",
    status: "approved",
    riskLevel: "low",
    fraudScore: 6,
    fraudStatus: "Clean",
    fraudFlags: [],
    manualReviewRequired: false,
    nextAction: "Benefit will be credited in the next cycle.",
    eta: "Completed",
    documentsPending: [],
    applicationId: "PM-KISAN-2024-8765432",
    createdAt: "2024-11-10T00:00:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Application Submitted",
        description: "Application was received successfully.",
        status: "completed",
        date: "10 November 2024",
      },
      {
        id: "s2",
        title: "Verification Complete",
        description: "Documents and land details were validated.",
        status: "completed",
        date: "21 November 2024",
      },
      {
        id: "s3",
        title: "Benefit Approved",
        description: "Application approved for payout.",
        status: "completed",
        date: "1 December 2024",
      },
    ],
  },
  {
    id: "demo-app-2",
    userId: "demo-user-3",
    schemeId: "3",
    schemeName: "Ayushman Bharat",
    citizenName: "Anjali Devi",
    ministry: "Ministry of Health and Family Welfare",
    state: "Bihar",
    status: "pending",
    riskLevel: "medium",
    fraudScore: 34,
    fraudStatus: "Clean",
    fraudFlags: [],
    manualReviewRequired: false,
    nextAction: "Wait for district verification team response.",
    eta: "5-7 working days",
    documentsPending: ["Family ID"],
    applicationId: "AYUSHMAN-2025-0122",
    createdAt: "2025-01-22T00:00:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Application Submitted",
        description: "Application was received successfully.",
        status: "completed",
        date: "22 January 2025",
      },
      {
        id: "s2",
        title: "Document Verification",
        description: "Family details are being validated.",
        status: "current",
      },
      {
        id: "s3",
        title: "Department Review",
        description: "The scheme department is reviewing your application.",
        status: "pending",
      },
    ],
  },
  {
    id: "demo-app-3",
    userId: "demo-user-2",
    schemeId: "4",
    schemeName: "Beti Bachao Beti Padhao",
    citizenName: "Priya Sharma",
    ministry: "Ministry of Women and Child Development",
    state: "Maharashtra",
    status: "under-review",
    riskLevel: "medium",
    fraudScore: 48,
    fraudStatus: "Flagged for review",
    fraudFlags: ["Profile needs manual verification before scholarship routing."],
    manualReviewRequired: true,
    nextAction: "Please upload additional education proof for review.",
    eta: "Manual review in progress",
    documentsPending: ["Education proof"],
    applicationId: "BETI-2025-0205",
    createdAt: "2025-02-05T00:00:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Application Submitted",
        description: "Application was received successfully.",
        status: "completed",
        date: "5 February 2025",
      },
      {
        id: "s0",
        title: "Fraud Review Screening",
        description: "Application was routed for additional verification.",
        status: "current",
        remarks: "Manual verification requested.",
      },
      {
        id: "s2",
        title: "Department Review",
        description: "The scheme department is reviewing your application.",
        status: "pending",
      },
    ],
  },
  {
    id: "demo-app-4",
    userId: "demo-user-4",
    schemeId: "5",
    schemeName: "Mudra Loan Yojana",
    citizenName: "Mohammed Rafiq",
    ministry: "Ministry of Finance",
    state: "Uttar Pradesh",
    status: "rejected",
    riskLevel: "high",
    fraudScore: 74,
    fraudStatus: "Flagged for review",
    fraudFlags: ["Income and business declarations failed consistency review."],
    manualReviewRequired: true,
    nextAction: "Please check eligibility and reapply with updated business records.",
    eta: "Closed",
    documentsPending: [],
    applicationId: "MUDRA-2025-0301",
    createdAt: "2025-03-01T00:00:00.000Z",
    steps: [
      {
        id: "s1",
        title: "Application Submitted",
        description: "Application was received successfully.",
        status: "completed",
        date: "1 March 2025",
      },
      {
        id: "s2",
        title: "Verification Review",
        description: "Business and financial details were reviewed.",
        status: "completed",
        date: "4 March 2025",
      },
      {
        id: "s3",
        title: "Final Decision",
        description: "Application was rejected after verification.",
        status: "error",
        date: "5 March 2025",
        remarks: "Eligibility mismatch found during business review.",
      },
    ],
  },
];

const sampleNotifications = [
  {
    id: "demo-note-1",
    userId: "demo-user-1",
    message: "Your PM Kisan application has been approved!",
    date: "2024-12-01",
  },
  {
    id: "demo-note-2",
    userId: "demo-user-3",
    message: "Your Ayushman Bharat application is under review.",
    date: "2025-01-25",
  },
  {
    id: "demo-note-3",
    userId: "demo-user-4",
    message: "Your Mudra Loan application was rejected. Please check eligibility.",
    date: "2025-03-05",
  },
];

module.exports = {
  sampleUsers,
  sampleSchemes,
  sampleApplications,
  sampleNotifications,
};
