export interface SchemeDetailRecord {
  id: string;
  name: string;
  category: string;
  ministry: string;
  state: string;
  officialUrl: string;
  portalLabel: string;
  helpline: string;
  benefitSummary: string;
  activeSince: string;
  beneficiaries: string;
  deadline: string;
  disclaimer: string;
  benefits: Array<{
    title: string;
    description: string;
  }>;
  eligibility: Array<{
    label: string;
    metByDefault?: boolean;
  }>;
  documents: Array<{
    name: string;
    required: boolean;
    purpose: string;
  }>;
  applicationSteps: string[];
  processingNote?: string;
}

export const schemeDetailRecords: SchemeDetailRecord[] = [
  {
    id: "1",
    name: "PM Kisan Samman Nidhi",
    category: "Agriculture",
    ministry: "Ministry of Agriculture and Farmers Welfare",
    state: "National",
    officialUrl: "https://pmkisan.gov.in",
    portalLabel: "PM-KISAN Portal",
    helpline: "155261 / 011-24300606",
    benefitSummary: "Rs. 6,000 per year in three instalments",
    activeSince: "2019",
    beneficiaries: "Small and marginal farmers",
    deadline: "Rolling enrollment",
    disclaimer: "SchemeConnect helps you prepare. Final application processing happens on the government portal.",
    benefits: [
      { title: "Direct income support", description: "Rs. 2,000 is transferred per instalment directly into the beneficiary bank account." },
      { title: "Pan-India coverage", description: "Eligible farmer households across states can enroll under the same central benefit." },
      { title: "DBT enabled", description: "Payments are routed through Aadhaar-seeded accounts for faster disbursal." },
    ],
    eligibility: [
      { label: "Applicant should be a farmer household", metByDefault: true },
      { label: "Land ownership records should be available", metByDefault: true },
      { label: "Bank account should be linked for DBT", metByDefault: true },
      { label: "Institutional landholders are not eligible", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification and Aadhaar-based authentication." },
      { name: "Land record", required: true, purpose: "Confirms ownership or cultivator details for the scheme record." },
      { name: "Bank passbook", required: true, purpose: "Used to validate the account receiving instalments." },
      { name: "Mobile number", required: false, purpose: "Helps receive OTPs and status updates from the portal." },
    ],
    applicationSteps: [
      "Open the PM-KISAN portal and select new farmer registration.",
      "Enter Aadhaar details and verify the farmer profile.",
      "Fill land, bank, and contact details exactly as per records.",
      "Submit and keep the acknowledgement for future instalment tracking.",
    ],
    processingNote: "You can also complete the registration through a Common Service Centre if local verification is needed.",
  },
  {
    id: "2",
    name: "PM Awas Yojana",
    category: "Housing",
    ministry: "Ministry of Housing and Urban Affairs",
    state: "National",
    officialUrl: "https://pmaymis.gov.in",
    portalLabel: "PMAY Official Portal",
    helpline: "1800-11-6446",
    benefitSummary: "Housing subsidy support for eligible families",
    activeSince: "2015",
    beneficiaries: "EWS, LIG, and housing-insecure households",
    deadline: "30 June 2026",
    disclaimer: "SchemeConnect does not approve housing benefits. Final verification is done by local authorities.",
    benefits: [
      { title: "Subsidy support", description: "Interest subsidy and housing support reduce the total cost of a pucca home." },
      { title: "Urban and rural impact", description: "The scheme supports housing improvement in both urban and local body workflows." },
      { title: "Women-focused ownership", description: "Many cases prioritize female or joint ownership in beneficiary records." },
    ],
    eligibility: [
      { label: "Household should not own a pucca house", metByDefault: true },
      { label: "Income should fit the approved category band", metByDefault: true },
      { label: "Applicant should meet local body verification rules", metByDefault: true },
      { label: "Duplicate housing support is not allowed", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Primary applicant identification for the housing record." },
      { name: "Income certificate", required: true, purpose: "Used to classify the family into the right subsidy band." },
      { name: "Residence proof", required: true, purpose: "Supports local jurisdiction and address validation." },
      { name: "No pucca house affidavit", required: false, purpose: "May be needed during scrutiny or local verification." },
    ],
    applicationSteps: [
      "Visit the PMAY portal and choose the relevant beneficiary category.",
      "Complete the applicant profile and housing information carefully.",
      "Upload income and residence records wherever required.",
      "Track the case through local body verification and sanction stages.",
    ],
  },
  {
    id: "3",
    name: "Ayushman Bharat",
    category: "Health",
    ministry: "Ministry of Health and Family Welfare",
    state: "National",
    officialUrl: "https://beneficiary.nha.gov.in",
    portalLabel: "Ayushman Bharat Beneficiary Portal",
    helpline: "14555",
    benefitSummary: "Health cover up to Rs. 5 lakh per family",
    activeSince: "2018",
    beneficiaries: "Priority and eligible families needing hospital support",
    deadline: "Open enrollment",
    disclaimer: "Eligibility and e-card issuance depend on official NHA systems and empanelled partners.",
    benefits: [
      { title: "Cashless treatment", description: "Eligible families can access treatment at empanelled hospitals without upfront payment." },
      { title: "High annual cover", description: "Hospitalization cover reaches up to Rs. 5 lakh per family each year." },
      { title: "Wide hospital network", description: "Treatment can be accessed across empanelled public and private hospitals." },
    ],
    eligibility: [
      { label: "Family must appear in the eligible beneficiary database", metByDefault: true },
      { label: "Identity details should match Aadhaar or family records", metByDefault: true },
      { label: "Family category must pass the official inclusion criteria", metByDefault: true },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity matching during beneficiary lookup or e-card generation." },
      { name: "Ration card", required: true, purpose: "Supports household and family record verification." },
      { name: "Family ID", required: true, purpose: "Helps validate members against the scheme database." },
      { name: "Mobile number", required: false, purpose: "Useful for OTP verification and notifications." },
    ],
    applicationSteps: [
      "Open the beneficiary portal and check whether your family appears in the official database.",
      "Verify identity details with Aadhaar or family records.",
      "Generate or update the Ayushman card through the authorized workflow.",
      "Use the card at an empanelled hospital when treatment is needed.",
    ],
    processingNote: "Card creation may also be completed through CSCs or empanelled hospitals if online verification stalls.",
  },
  {
    id: "4",
    name: "Beti Bachao Beti Padhao",
    category: "Education",
    ministry: "Ministry of Women and Child Development",
    state: "National",
    officialUrl: "https://wcd.nic.in",
    portalLabel: "Women and Child Development Portal",
    helpline: "181",
    benefitSummary: "Awareness, education support, and girl-child welfare convergence",
    activeSince: "2015",
    beneficiaries: "Girl children and their families",
    deadline: "Program-based enrollment",
    disclaimer: "This scheme often works through district and institutional channels rather than a single central application flow.",
    benefits: [
      { title: "Girl-child support", description: "Promotes education continuation and access to supporting welfare measures." },
      { title: "District convergence", description: "Links child development, education, and local campaign benefits together." },
      { title: "Social awareness", description: "Improves awareness against gender bias while improving service access." },
    ],
    eligibility: [
      { label: "Applicant should fall under girl-child focused support", metByDefault: true },
      { label: "Relevant school or district records may be required", metByDefault: true },
      { label: "Benefits can vary by state or district execution", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Used for identity verification where Aadhaar-based records are accepted." },
      { name: "School certificate", required: true, purpose: "Shows the educational status of the child where required." },
      { name: "Income certificate", required: false, purpose: "May be requested for linked scholarship or benefit routing." },
      { name: "Residence proof", required: false, purpose: "Supports district-level routing or local service delivery." },
    ],
    applicationSteps: [
      "Confirm the active district or state workflow for the support being claimed.",
      "Collect school and identity records in advance.",
      "Submit through the relevant institutional or local welfare channel.",
      "Keep district acknowledgement details for future follow-up.",
    ],
  },
  {
    id: "5",
    name: "Mudra Loan Yojana",
    category: "Finance",
    ministry: "Ministry of Finance",
    state: "National",
    officialUrl: "https://www.mudra.org.in",
    portalLabel: "MUDRA Official Portal",
    helpline: "1800-180-1111",
    benefitSummary: "Business loan support up to Rs. 10 lakh",
    activeSince: "2015",
    beneficiaries: "Micro and small business owners",
    deadline: "Open enrollment",
    disclaimer: "SchemeConnect can help you prepare documents, but loan sanction is decided by the lending institution.",
    benefits: [
      { title: "Business capital access", description: "Provides entry-level financing for micro and small enterprise activity." },
      { title: "Category-based loan options", description: "Shishu, Kishore, and Tarun categories support different business stages." },
      { title: "Broad bank coverage", description: "Public, private, and regional lenders may process eligible requests." },
    ],
    eligibility: [
      { label: "Applicant should run or propose a small enterprise", metByDefault: true },
      { label: "Business plan and repayment potential should be clear", metByDefault: true },
      { label: "Final sanction depends on lender underwriting", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification for the borrower." },
      { name: "PAN card", required: true, purpose: "Supports KYC and lending compliance where needed." },
      { name: "Bank statement", required: true, purpose: "Helps the lender review business or applicant cash flow." },
      { name: "Business plan", required: true, purpose: "Explains how the requested capital will be used." },
    ],
    applicationSteps: [
      "Prepare a short business profile and capital requirement summary.",
      "Choose a participating bank or lender and begin the Mudra application.",
      "Submit KYC, banking, and business documents.",
      "Track appraisal, sanction, and disbursal with the lending branch.",
    ],
  },
  {
    id: "6",
    name: "Rajiv Gandhi Scholarships",
    category: "Education",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://sevasindhu.karnataka.gov.in",
    portalLabel: "Seva Sindhu Portal",
    helpline: "080-4455-4455",
    benefitSummary: "Scholarship support for eligible Karnataka students",
    activeSince: "State rollout",
    beneficiaries: "Priority student categories in Karnataka",
    deadline: "Academic cycle based",
    disclaimer: "Scholarship release depends on institution and state-level verification.",
    benefits: [
      { title: "Student financial support", description: "Helps reduce the cost burden of continuing education." },
      { title: "State-linked delivery", description: "Routes benefits through Karnataka's student welfare workflows." },
      { title: "Academic continuity", description: "Supports continuation for eligible learners from priority backgrounds." },
    ],
    eligibility: [
      { label: "Applicant should be enrolled in an eligible course", metByDefault: true },
      { label: "Category and income conditions may apply", metByDefault: true },
      { label: "Institution verification is usually mandatory", metByDefault: true },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity and student profile verification." },
      { name: "Mark sheet", required: true, purpose: "Confirms academic eligibility and continuation." },
      { name: "Income certificate", required: true, purpose: "Supports scholarship category evaluation." },
      { name: "Bank passbook", required: true, purpose: "Required for direct benefit transfer." },
    ],
    applicationSteps: [
      "Check the active student scholarship window for your course.",
      "Collect academic, identity, and income records.",
      "Submit the application through the state portal or institutional workflow.",
      "Follow up with institution verification if the application remains pending.",
    ],
  },
  {
    id: "7",
    name: "MGNREGA",
    category: "Employment",
    ministry: "Ministry of Rural Development",
    state: "National",
    officialUrl: "https://nrega.nic.in",
    portalLabel: "MGNREGA Portal",
    helpline: "1800-111-555",
    benefitSummary: "Up to 100 days of rural wage employment",
    activeSince: "2005",
    beneficiaries: "Rural households seeking guaranteed wage work",
    deadline: "Open enrollment",
    disclaimer: "Actual work allocation and job card management are handled through local rural administration.",
    benefits: [
      { title: "Guaranteed wage employment", description: "Rural households can demand wage work under the program." },
      { title: "Job card system", description: "Registered households receive a local work identity document." },
      { title: "Rural livelihood support", description: "Helps stabilize household income during periods of low employment." },
    ],
    eligibility: [
      { label: "Applicant should belong to a rural household", metByDefault: true },
      { label: "Job card enrollment or demand registration is required", metByDefault: true },
      { label: "Work is allocated through local panchayat processes", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Used for identity and local registration." },
      { name: "Residence proof", required: true, purpose: "Confirms the rural household and local jurisdiction." },
      { name: "Bank passbook", required: true, purpose: "Needed for wage transfers." },
      { name: "Photograph", required: false, purpose: "May be needed while creating or updating the job card." },
    ],
    applicationSteps: [
      "Visit the Gram Panchayat or approved local channel to request a job card.",
      "Submit identity and residence proof for household registration.",
      "Demand work formally after the job card is issued.",
      "Track work allocation and wage credit through the official portal or local office.",
    ],
  },
  {
    id: "8",
    name: "National Scholarship Portal",
    category: "Education",
    ministry: "Ministry of Education",
    state: "National",
    officialUrl: "https://scholarships.gov.in",
    portalLabel: "National Scholarship Portal",
    helpline: "0120-6619540",
    benefitSummary: "Centralized scholarship access for multiple schemes",
    activeSince: "Central portal rollout",
    beneficiaries: "Students across categories and institutions",
    deadline: "Academic cycle based",
    disclaimer: "SchemeConnect can guide preparation, but scholarship approval depends on NSP and institution verification.",
    benefits: [
      { title: "Single scholarship gateway", description: "Access multiple scholarship programs from one official portal." },
      { title: "Institution-linked processing", description: "Applications move through student, institute, and nodal review stages." },
      { title: "Bank-ready disbursal", description: "Approved scholarship amounts are transferred through DBT workflows." },
    ],
    eligibility: [
      { label: "Applicant must be enrolled in a recognized institution", metByDefault: true },
      { label: "Income and category criteria depend on the chosen scholarship", metByDefault: true },
      { label: "Academic records should satisfy renewal or fresh application rules", metByDefault: true },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Supports identity verification on the portal." },
      { name: "Previous mark sheet", required: true, purpose: "Used to verify merit and continuation eligibility." },
      { name: "Income certificate", required: true, purpose: "Needed for means-tested scholarships." },
      { name: "Bonafide certificate", required: false, purpose: "Often required by the institution workflow." },
    ],
    applicationSteps: [
      "Create or log in to your NSP account during the active application window.",
      "Choose the correct scholarship and fill academic details accurately.",
      "Upload all mandatory records and submit for institute verification.",
      "Track status through institute, nodal, and final sanction stages.",
    ],
  },
  {
    id: "13",
    name: "Gruha Lakshmi Scheme",
    category: "Women Welfare",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://sevasindhu.karnataka.gov.in",
    portalLabel: "Seva Sindhu Portal",
    helpline: "1902",
    benefitSummary: "Rs. 2,000 per month for the woman head of household",
    activeSince: "2023",
    beneficiaries: "Women heads of eligible families in Karnataka",
    deadline: "Rolling enrollment",
    disclaimer: "Final beneficiary approval and payout are governed by the Karnataka state system.",
    benefits: [
      { title: "Monthly income support", description: "Provides Rs. 2,000 each month to the eligible woman head of household." },
      { title: "Direct bank credit", description: "Funds move into the registered bank account after approval." },
      { title: "State-family linkage", description: "Uses ration and household records to confirm the beneficiary." },
    ],
    eligibility: [
      { label: "Applicant should be the recognized woman head of family", metByDefault: true },
      { label: "Karnataka household records should match submitted details", metByDefault: true },
      { label: "Bank account should be active and DBT-ready", metByDefault: true },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Primary identity check for the beneficiary." },
      { name: "Ration card", required: true, purpose: "Used to confirm family and head-of-household status." },
      { name: "Bank passbook", required: true, purpose: "Supports direct benefit transfer to the right account." },
      { name: "Residence proof", required: false, purpose: "May be needed if household records need correction." },
    ],
    applicationSteps: [
      "Open Seva Sindhu and choose the Gruha Lakshmi service.",
      "Verify the woman head of household details with family records.",
      "Submit Aadhaar-linked bank information and contact details.",
      "Track approval and payment status through the state portal.",
    ],
  },
  {
    id: "14",
    name: "Yuva Nidhi Scheme",
    category: "Employment",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://sevasindhu.karnataka.gov.in",
    portalLabel: "Seva Sindhu Portal",
    helpline: "1902",
    benefitSummary: "Monthly unemployment assistance for eligible youth",
    activeSince: "2023",
    beneficiaries: "Eligible unemployed graduates and diploma holders",
    deadline: "Open enrollment",
    disclaimer: "Payment continuation depends on eligibility and periodic state checks.",
    benefits: [
      { title: "Graduate support", description: "Eligible graduates can receive monthly assistance during unemployment." },
      { title: "Diploma support", description: "Eligible diploma holders can also access reduced monthly support." },
      { title: "Time-bound assistance", description: "Support is typically available for a limited benefit duration." },
    ],
    eligibility: [
      { label: "Applicant should be an eligible unemployed youth", metByDefault: true },
      { label: "Educational qualification should match the program category", metByDefault: true },
      { label: "State verification may require continued unemployment status", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification for the applicant." },
      { name: "Degree or diploma certificate", required: true, purpose: "Confirms education-based eligibility." },
      { name: "Bank passbook", required: true, purpose: "Used to transfer the monthly support amount." },
      { name: "Employment registration proof", required: false, purpose: "May support unemployment verification." },
    ],
    applicationSteps: [
      "Start the Yuva Nidhi service on Seva Sindhu.",
      "Fill personal, education, and employment details accurately.",
      "Upload qualification and bank documents.",
      "Track the approval cycle and monthly disbursal updates on the portal.",
    ],
  },
  {
    id: "15",
    name: "Anna Bhagya Scheme",
    category: "Food Security",
    ministry: "Department of Food, Civil Supplies and Consumer Affairs",
    state: "Karnataka",
    officialUrl: "https://ahara.kar.nic.in",
    portalLabel: "Ahara Karnataka Portal",
    helpline: "1967",
    benefitSummary: "Food security support for eligible priority households",
    activeSince: "State rollout",
    beneficiaries: "BPL and priority ration card households",
    deadline: "Open enrollment",
    disclaimer: "Actual distribution depends on ration card status and the public distribution workflow.",
    benefits: [
      { title: "Household food support", description: "Supports monthly food entitlement for eligible families." },
      { title: "Ration-linked delivery", description: "Runs through the public distribution system and fair price shops." },
      { title: "Household coverage", description: "Benefits are tied to registered family records and ration status." },
    ],
    eligibility: [
      { label: "Household should hold the right ration card category", metByDefault: true },
      { label: "Aadhaar seeding may be required for family records", metByDefault: true },
      { label: "Distribution depends on PDS verification", metByDefault: false },
    ],
    documents: [
      { name: "Ration card", required: true, purpose: "Primary record for entitlement under the distribution system." },
      { name: "Aadhaar card", required: true, purpose: "Links family members to ration records where required." },
      { name: "Residence proof", required: false, purpose: "Useful if household address updates are needed." },
    ],
    applicationSteps: [
      "Check your ration card status and category on the Ahara portal.",
      "Ensure Aadhaar and family records are correctly linked.",
      "Update any record mismatches through the local ration workflow if needed.",
      "Collect benefits through the approved distribution channel.",
    ],
  },
  {
    id: "16",
    name: "Shakti Scheme",
    category: "Transport",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://sevasindhu.karnataka.gov.in",
    portalLabel: "Seva Sindhu Portal",
    helpline: "1902",
    benefitSummary: "Free bus travel for eligible women in Karnataka",
    activeSince: "2023",
    beneficiaries: "Women commuters using state-run bus services",
    deadline: "Open enrollment",
    disclaimer: "Usage is subject to service rules and supported transport operators.",
    benefits: [
      { title: "Free state bus travel", description: "Reduces recurring transport cost for eligible women commuters." },
      { title: "Daily mobility support", description: "Improves access to work, education, and services." },
      { title: "Identity-based validation", description: "Travel benefits rely on recognized identity and state validation rules." },
    ],
    eligibility: [
      { label: "Applicant should be an eligible woman commuter", metByDefault: true },
      { label: "State identity proof should be available", metByDefault: true },
      { label: "Travel benefit applies only on supported services", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification where Aadhaar is accepted." },
      { name: "Photo ID", required: true, purpose: "Used during travel validation or registration checks." },
      { name: "Residence proof", required: false, purpose: "May support state linkage if profile corrections are needed." },
    ],
    applicationSteps: [
      "Verify the latest Shakti registration or identity rules on Seva Sindhu.",
      "Complete any required beneficiary verification.",
      "Keep the approved identity proof ready while traveling.",
      "Use the benefit on supported Karnataka state bus services.",
    ],
  },
  {
    id: "17",
    name: "Arogya Karnataka",
    category: "Health",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://arogya.karnataka.gov.in",
    portalLabel: "Arogya Karnataka Portal",
    helpline: "104",
    benefitSummary: "Health support for eligible Karnataka families",
    activeSince: "State rollout",
    beneficiaries: "Eligible families in Karnataka needing hospital support",
    deadline: "Open enrollment",
    disclaimer: "Treatment availability depends on official enrollment status and empanelled hospital processes.",
    benefits: [
      { title: "Hospital support", description: "Eligible families can access treatment assistance through state health workflows." },
      { title: "Linked family health records", description: "Family status and eligibility drive approval within the system." },
      { title: "Empanelled provider access", description: "Support is delivered through recognized treatment facilities." },
    ],
    eligibility: [
      { label: "Applicant should belong to an eligible Karnataka household", metByDefault: true },
      { label: "Identity and family records should be consistent", metByDefault: true },
      { label: "Hospital usage depends on official scheme validation", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification for patient and family records." },
      { name: "BPL card", required: true, purpose: "Supports eligibility confirmation for priority categories." },
      { name: "Ration card", required: true, purpose: "Links the family record used by the scheme." },
    ],
    applicationSteps: [
      "Review household eligibility through the official state health workflow.",
      "Verify Aadhaar and family-linked records before enrollment.",
      "Generate or confirm the scheme-linked health record if required.",
      "Use the approved benefit through empanelled facilities.",
    ],
  },
  {
    id: "18",
    name: "Raitha Siri Scheme",
    category: "Agriculture",
    ministry: "Government of Karnataka",
    state: "Karnataka",
    officialUrl: "https://raitamitra.karnataka.gov.in",
    portalLabel: "Raitha Mitra Portal",
    helpline: "1800-425-3553",
    benefitSummary: "Targeted assistance for eligible farmers",
    activeSince: "State support program",
    beneficiaries: "Eligible farmers in Karnataka",
    deadline: "31 July 2026",
    disclaimer: "Benefit release depends on agriculture department verification and district processing.",
    benefits: [
      { title: "Farmer assistance", description: "Supports eligible farming households with targeted financial help." },
      { title: "State agriculture workflow", description: "Applications are reviewed through Karnataka agriculture channels." },
      { title: "Record-based verification", description: "Land and beneficiary records are important during approval." },
    ],
    eligibility: [
      { label: "Applicant should be an eligible farmer", metByDefault: true },
      { label: "Land or cultivation records should be available", metByDefault: true },
      { label: "District agriculture verification may be required", metByDefault: false },
    ],
    documents: [
      { name: "Aadhaar card", required: true, purpose: "Identity verification for farmer records." },
      { name: "Land records", required: true, purpose: "Confirms farm ownership or cultivation details." },
      { name: "Bank passbook", required: true, purpose: "Used for direct transfer of approved assistance." },
      { name: "Caste or income certificate", required: false, purpose: "May be requested under specific state conditions." },
    ],
    applicationSteps: [
      "Check the active Raitha Siri application window and district instructions.",
      "Collect land, identity, and bank records in advance.",
      "Submit through the designated agriculture portal or district workflow.",
      "Track verification and benefit release with the state agriculture system.",
    ],
  },
];

export const schemeDetailsById = Object.fromEntries(
  schemeDetailRecords.map((record) => [record.id, record]),
) as Record<string, SchemeDetailRecord>;
